- lesspass.sh
The date-method you've used is okay for unique passwords but they're not random, but a truly good passwort has to be. Therefore i propose this PR which uses the systems random pool to generate the same 32 char long passwords - but now they're not just unique but also random. Also as an additional password enhancement i've added the underline to the possible password (harder to crack).
I've successfully tested this new method on Debian and macOS Sierra. This should work on almost all Linux/Unix systems.
To mention the LC_ALL=C thing. This is sometimes necessary for `tr` to work. Otherwise you can get an `tr: Illegal byte sequence` on macOS systems.
> Changed password-generation method for DB and secret key

- lesspass.sh
- readme.md
I suggest to allow lesspass installation script to take the requested domain as parameter so that it can be installed in a non interactive way.
> Allow lesspass.sh to take the domain as argument

- README.md
As it opens ```https://github.com/lesspass/lesspass/blob/master/graphs/contributors``` (404) if not
> Put the entire contributors URL

- cli/lesspass/cli.py
- cli/lesspass/core.py
- cli/lesspass/help.py
- cli/lesspass/validator.py
- cli/tests/test_cli.py
- cli/tests/test_validator.py
For added security, this PR provides a [-p --prompt] argument which then allows a user to enter both the SITE and LOGIN arguments in the same manner they could enter the MASTER PASSWORD - without revealing their values in a terminal buffer, or recording them in bash history.
Usage:
```
$ lesspass -p -L 25
Site: 
Login: 
Master Password: 
ybnAY]&S?Vx\8L,96u!_?,;>J
```
> Adds an argument to prompt for the [SITE] and [LOGIN] arguments

- .travis.yml
* ~set `PYTHONPATH` to [fix integration test](https://travis-ci.org/lesspass/lesspass/jobs/484259455).~ fixed by 820922a
* add `name`s to travis stages
> Fix add names to travis stages

- cli/lesspass/help.py
Fixes #390 
Nothing major going on here, just a quick clarification that the possible length is capped at 35. I'll look further to investigate why the additional `a` is being appended to make up for the length, but for now this should suffice.
> adding help text clarity around supported max-length

- cli/lesspass/cli.py
- cli/lesspass/core.py
@guillaumevincent Thanks for your assistance working with me on #395!
A bug has been introduced in the formatting commit that prevents us from using the `--prompt` flag.
```shell
$ lesspass --version
7.0.0
$ lesspass --prompt
usage: lesspass SITE [LOGIN] [MASTER_PASSWORD] [OPTIONS]
lesspass: error: the following arguments are required: site
```
This is because of the removal of `nargs=` [here](https://github.com/lesspass/lesspass/commit/b310f00cb8610f7a3ceb252b4fae885dbe6382cb#diff-8c53b6fdc68a0ec41b6e1ba38f7247ddR40). In my initial testing I had also removed it, but I [noted](https://github.com/lesspass/lesspass/commit/cb360754f192d4cdf1a114a6788049649c1a7d8d#diff-8c53b6fdc68a0ec41b6e1ba38f7247ddR42) that removing it caused an issue with the CLI being expected to accept a SITE via …
> fix bug preventing the usage of --prompt

- packages/lesspass-web-extension/extension/popup.html
This prevents scroll bars from appearing when options are displayed on the main screen.
Quick preview of all the views on chrome/firefox:
> Allow the browser to dynamically resize the popup window

- containers/frontend/dist/i18n/de.json
- containers/frontend/dist/i18n/en.json
It looks like de and en translations are mixed with "LengthDeprecationWarning" variable.
> Fixing en/de mismatch with LengthDeprecationWarning

- packages/lesspass-pure/src/views/PasswordGenerator.vue
closes: #431 
The issue seemed to be caused by a missing timeout to hide the tooltip element. For the fix, I just followed the format for hiding the tooltip [a few lines above](https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/src/views/PasswordGenerator.vue#L238). 
Before:
After:
I didn't include changes to [`lesspass-web-extension/extension/dist/lesspass.min.js`](https://github.com/lesspass/lesspass/blob/master/packages/lesspass-web-extension/extension/dist/lesspass.min.js), but let me know if I should add a commit for it.
> Add timeout for share password profile popup

- cli/lesspass/__init__.py
- cli/setup.py
Potential fix for #405. Looks like the longer description was removed in #395, which was intentional:
> A short plain-text description (defined in module `__init__`) has been added to this file to replace this entirely at the discretion of the maintainers. This will have an impact on how the package appears on PyPi, but as the text on PyPi was not monospaced, the help-output may not be best for this space anyway.
If the longer description is better for Pypi, this fix should add it back in and leave the shorter description available for use. Otherwise both this issue and #405 can be closed.
> Add longer description for Pypi docs

- cli/lesspass/clipboard.py
- cli/lesspass/core.py
The lesspass CLI already supports copying to the clipboard on X
window system environments if certain tools (xsel or xclip) are
installed. Many Unix-like systems have begun shipping environments
that use Wayland instead of X. xsel and xclip are not designed for
Wayland. The most widely-used clipboard tool suite for Wayland,
wl-clipboard, has an optional compatibility layer that can make it
work with the xsel and xclip commands; this may or may not be
included in packages that provide the wl-clipboard tools.
This commit gives the lesspass CLI explicit support for the wl-copy
command provided by wl-clipboard. lesspass will continue to check
for the presence of xsel and xclip before trying wl-copy, to guard
against the perhaps unlikely scenario that the user has the wl-copy
command installed …
> Add explicit CLI support for wl-clipboard

- cli/lesspass/clipboard.py
It has been pointed out by @bugaevc that a user may have X and
Wayland software available on the same system (e.g. for testing
purposes) and that the best way to determine whether to use
xsel/xclip or wl-copy is not to merely check for the presence of
these commands, but to check whether the `WAYLAND_DISPLAY`
environment variable is set. That is what this commit does.
@guillaumevincent, we were just discussing this.
> Check DISPLAY_WAYLAND env variable to decide whether to use wl-copy

- cli/lesspass/core.py
This is a small change which reorders/consolidates how lesspass prompts the user for the required information. Before this, if a user supplied the -p tag while also providing site, login, and or a password in the positional arguments, the prompt would ask for the values again. This instead checks for the values and skips asking if they exist. For example, "lesspass sitename -p" will only prompt for the login and the password
> fix duplicate prompts

- packages/lesspass-pure/src/i18n/es.json
While using the browser extension i noticed you use roughly the same spanish translation for "Sign up" and "Sign in". This is confusing because whenever i want to sign in i forget which of the two buttons is supposed to do it.
So i replaced it with a far more common translation.
> Fix spanish translation error: changed 'Sign in' translation from 'Registrarse' to 'Ingresar'

- cli/lesspass/clipboard.py
Hi!
I've experienced some issues on Termux (Android).
After some research, I found that the use of the `which` command in `subprocess.call()` can cause some issues, as it is well explained [here](https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script):
> Avoid which. Not only is it an external process you're launching for doing very little (meaning builtins like hash, type or command are way cheaper), you can also rely on the builtins to actually do what you want, while the effects of external commands can easily vary from system to system.
>
> Why care?
> - Many operating systems have a which that doesn't even set an exit status, meaning the if which foo won't even work there and will always report that foo exists, even if it doesn't (note that …
> More robust command check for cli

- cli/lesspass/fingerprint.py
Modules tty and termios will not be used in Windows.
If import tty and termios in Windows, it will raise `ModuleNotFoundError` like [lesspass#556](https://github.com/lesspass/lesspass/issues/556).
> Not import tty and termios when in NT os

- containers/webserver/httpd-ssl.conf
- containers/webserver/httpd.conf
Apache start to support HTTP/2 since v2.4.17, this will make the web loading much more faster!
> Enable Apache HTTP/2 for better performance

- containers/webserver/httpd-ssl.conf
This will speed up the website loading, and make the website more
reliable to the users when the client fails to connect to the CA for an
OCSP response.
Reference:
- https://en.wikipedia.org/wiki/OCSP_stapling
> Enable Apache OCSP stapling

- packages/lesspass-site/nginx.conf
It's suggested to minimized the unnecessary information disclosure as
part of the nginx hardening practice.
Current config will send the version of nginx in the header of every request:
```sh
$ curl -sI https://lesspass.com | grep ^Server:
Server: nginx/1.19.2
```
> Turn off nginx server_tokens for lesspass-site

- containers/webserver/Dockerfile
- containers/webserver/httpd.conf
The header of Apache's `Server` header may also disclosure too much unnecessary information.
```sh
$ curl -sI --no-location http://lesspass.com | grep ^Server
Server: Apache/2.4.46 (Unix) OpenSSL/1.1.1d
```
cc #568
> Minimize Apache ServerTokens for lesspass-site

- bin/build_web_extensions
- bin/build_web_site
- cli/tests/test_functional.py
- containers/backend/Dockerfile
- containers/ssl/create_ca_and_ee.sh
- containers/webserver/Dockerfile
- mobile/android/app/src/main/java/com/lesspass/android/Crypto.java
- mobile/ios/LessPassModule.swift
- packages/lesspass-site/Dockerfile
Should better to integrate linter in CI to make sure the future changes also follows the `.editorconfig` for better styling.
> Remove trailing spaces in text files, following .editorconfig

- .editorconfig
Current httpd*.conf files are copied from httpd:2.4 Docker official
images which has trailing spaces, but not added by the project, should
be ignored.
> Allow httpd*.conf under containers/webserver has trailing spaces

- .editorconfig
- bin/build_web_extensions
- bin/build_web_site
There were few indents using 3 spaces or tabs in the shell scripts under `bin/` directory, looks like they should be 4 spaces as the most other places use 4 spaces.
> Fix shell script indentation as it's 4 spaces here

- containers/backend/Dockerfile
This will make the backend image much smaller 🎉 
```
REPOSITORY                       TAG                IMAGE ID       CREATED          SIZE
after                            latest             ecd8a33f45fc   5 minutes ago    211MB
before                           latest             58b7dae3e4f0   13 minutes ago   235MB
```
> Leave no Python pip temporary cache in backend Docker image

- .github/workflows/cli-publish.yml
- .github/workflows/cli-test.yml
- .github/workflows/containers-publish.yml
- .github/workflows/containers-test.yml
- .github/workflows/lesspass-crypto-publish.yml
- .github/workflows/lesspass-crypto-test.yml
- .github/workflows/lesspass-entropy-publish.yml
- .github/workflows/lesspass-entropy-test.yml
- .github/workflows/lesspass-fingerprint-publish.yml
- .github/workflows/lesspass-fingerprint-test.yml
- .github/workflows/lesspass-publish.yml
- .github/workflows/lesspass-pure-publish.yml
- .github/workflows/lesspass-pure-test.yml
- .github/workflows/lesspass-render-password-publish.yml
- .github/workflows/lesspass-render-password-test.yml
- .github/workflows/lesspass-test.yml
- .github/workflows/mobile-test.yml
Reference:
- https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> Update GitHub Actions env, replace EOL-ed Ubuntu 18.04 w/ Ubuntu 22.04

- mobile/src/password/MasterPassword.js
- mobile/src/password/PasswordGeneratorScreen.js
- mobile/src/ui/TextInput.js
This PR introduces UX enhancements to the password generator screen on mobile. The updates to the `PasswordGeneratorScreen` include:
- Auto-focus on the 'site' input field.
- The next button on the keyboard shifts focus to the subsequent text input.
- The done button on the master password field (last text input) triggers password generation.
fixes #778
> Mobile: Fix keyboard navigation in PasswordGeneratorScreen
